// NUMBER GUESSING GAME (MINI PROJECT)

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main()
{
    // Seed the random number generator using the current time
    srand(time(0));

    // Variable to store the number of guesses taken by the player
    int count = 0;

    // Variable to store the random number generated by the computer
    int x;

    // Variable to store the player's guess
    int guess;

    // Generate a random number between 1 and 100
    x = rand() % 100 + 1;

    // Display the game title
    printf("=== NUMBER GUESSING GAME ===\n");

    // Keep running the game until the player guesses the correct number
    while (1)
    {
        // Ask the player to enter a number
        printf("\nEnter your guess number (1-100): ");
        scanf("%d", &guess);

        // Increase the guess count after every attempt
        count++;

        // Check if the guessed number is correct
        if (guess == x)
        {
            printf("\nCONGRATULATIONS!\n");
            printf("THE NUMBER %d YOU GUESSED IS CORRECT.\n", guess);

            // Exit the loop because the correct number was guessed
            break;
        }

        // If the guess is greater than the actual number
        else if (guess > x)
        {
            printf("LOWER NUMBER PLEASE.\n");
        }

        // If the guess is smaller than the actual number
        else
        {
            printf("HIGHER NUMBER PLEASE.\n");
        }
    }

    // Display the total number of guesses taken by the player
    printf("\nTHE NUMBER OF GUESSES TAKEN BY YOU IS: %d\n", count);

    return 0;
}
